require('settings')
require('colorchemes-config.doom-one')
require('packer-config')
require('mappings')
require('plugin-config.nvim-tree')
require('plugin-config')
require('lsp-config.lenguage-server')
